language: node_js

node_js:
  - "5.2"

install:
  - npm install
  - npm run typings
  # - npm install && npm install codecov.io

# after_success:
#   - cat ./coverage/lcov.info | ./node_modules/.bin/codecov
