/* eslint comma-dangle: [2, "always-multiline"] */
module.exports = {
  version: require('./package').version,
  dijkstra: require('./alg/dijkstra'),
  kruskal: require('./alg/kruskal'),
  sqrt: require('./alg/sqrt'),
  binarySearch: require('./alg/binary-search'),
  longestIncreasingSubsequence: require('./alg/longest-increasing-subsequence'),
  permutation: require('./alg/permutation'),
  bracket: require('./alg/bracket'),
  powerset: require('./alg/powerset'),
  life: require('./alg/life'),
  joinSet: require('./alg/join-set'),
  telword: require('./alg/telword'),
  smallestBiggerWithSameDigits: require('./alg/smallest-bigger-with-same-digits'),
  palindrome: require('./alg/palindrome.js'),
  kmp: require('./alg/kmp.js'),
  isBalanced: require('./alg/is-balanced.js'),
  sort: require('./alg/sort'),
  knapsack: require('./alg/knapsack'),
  longestCommonSubsequence: require('./alg/longest-common-subsequence'),
  montyHall: require('./alg/monty-hall'),
  gcd: require('./alg/gcd'),
};
